---
title: Project 2 - Soundscape Metric Interpretation & Visualization
---

### Goal and Target Outcome

We will create a set of soundscape metric interpretation open-source processing pathways and visualizations for cross-FMCs comparisons and FMCs-specific soundscape priorities.

### Summary

This project will build on existing tools in PAMscapes (R/CRAN) to create and document processing pathways for soundscape metric interpretation. NOAA Noise Reference Station soundscape metrics will be used to build the pathways and evaluate outputs. Additional soundscape metrics from PAM SI priority data sets will be incorporated based on availability from Soundscape Priority #1 Projects (above). We will create decision-support tools that are relevant at regional and national scales and integrate PAM data with variables to provide context for different soundscapes (environmental data, species-detections, etc).


## Establish working group
*Establish working group and create folder in shared Google doc folder.*

## Identify datasets
*Decide on priority Noise Reference Station (NRS) datasets for metric development.*

## Data products to NCEI
*NRS Hybrid Milli-Decade (HMD) products to be included in initial comparison sent to NCEI.*

## Identify visualization options
*Organize and expand on options for HMD data visualizations as originally prepared for PAMscapes, share with working group via Google doc folder for discussion of level 1 visualization goals. Ideas and inspiration will be organized for project team brainstorming and feedback meeting.*

## Develop workplan
*Set-up work plan with Taiki Sakai to evaluate HMD QA/QC with visualizations in PAMscapes including level 1 visualizations such as percentiles, LTSA, and bringing together MANTA and pyPAM default outputs.*

## Present initial results
*Updated PAMscapes tool for HMD QA/QC level 1 visualization will be shared with project team for feedback and further development.*

## Level 2 data product planning
*In coordination with QA/QC tool development, and informed by ongoing collaboration with SoundCoop partners, the Soundscape group will develop level 2 visualization for HMD output by: integrating environmental data (currents, wind, ice, etc.) and time/frequency bins for quantitative visualization (e.g., SPD). The option to integrate these visualizations as additional PAMscapes functionality or publish as separate code on GitHub will be evaluated.*

## Level 3 data product planning
*Plan the development level 3 products from HMD that prioritize and reflect the needs of SI and FMCs including: integration with PACM; noise budgets; sound propagation; automated soundscape analysis; co-variate for species models; categorization from HMD data; repository of labeled HMD data; integration of AIS data.*

## Cloud processing
*Following Cloud Computing project Phase 7 (Software phase II validation), conduct cloud processing for HMD and PAMscapes to apply relevant methods on FMCs priority datasets.*

## Facilitate national comparisons
*Develop additional products or visualizations for nationwide comparison of FMC priority soundscapes.*

## Present project outcomes
*Present tested and functional cloud processing routines for level 1-3 products for all priority data sets for PAM SI reporting and additional science needs.*
